--
-- PostgreSQL database dump
--

\restrict g5AwCb01ynCenhAy2YSFLubKyKXPm6s3tqPbqYLeWgYpM1bhJCcXqOgaYg2GdCE

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 15.14 (Debian 15.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: course; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.course (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    teacher character varying(255),
    title character varying(255) NOT NULL
);


ALTER TABLE public.course OWNER TO admin;

--
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grades; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.grades (
    id bigint NOT NULL,
    score double precision NOT NULL,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT grades_score_check CHECK (((score <= (20)::double precision) AND (score >= (0)::double precision)))
);


ALTER TABLE public.grades OWNER TO admin;

--
-- Name: grades_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.grades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(50) NOT NULL
);


ALTER TABLE public.students OWNER TO admin;

--
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: course; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.course (id, code, teacher, title) FROM stdin;
\.


--
-- Data for Name: grades; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.grades (id, score, course_id, student_id) FROM stdin;
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.students (id, first_name, last_name) FROM stdin;
\.


--
-- Name: course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.course_id_seq', 1, false);


--
-- Name: grades_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.grades_id_seq', 1, false);


--
-- Name: students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.students_id_seq', 1, false);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- Name: grades grades_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT grades_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: course uki60mruj0y7a7vs99dqpiye7en; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT uki60mruj0y7a7vs99dqpiye7en UNIQUE (code);


--
-- Name: grades fk13a16545m7vvrcspc999r15s9; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fk13a16545m7vvrcspc999r15s9 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: grades fkaww3gy2x6kx6s2uc3taeujuap; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fkaww3gy2x6kx6s2uc3taeujuap FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- PostgreSQL database dump complete
--

\unrestrict g5AwCb01ynCenhAy2YSFLubKyKXPm6s3tqPbqYLeWgYpM1bhJCcXqOgaYg2GdCE

