-- V1: Initial schema from existing database

-- Table: course
CREATE TABLE course (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    teacher character varying(255),
    title character varying(255) NOT NULL
);

ALTER TABLE course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: grades
CREATE TABLE grades (
    id bigint NOT NULL,
    score double precision NOT NULL,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT grades_score_check CHECK (((score <= 20) AND (score >= 0)))
);

ALTER TABLE grades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME grades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: students
CREATE TABLE students (
    id bigint NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(50) NOT NULL
);

ALTER TABLE students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: users
CREATE TABLE users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['USER', 'ADMIN'])))
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary Keys
ALTER TABLE ONLY course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);

ALTER TABLE ONLY grades
    ADD CONSTRAINT grades_pkey PRIMARY KEY (id);

ALTER TABLE ONLY students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Unique Constraints
ALTER TABLE ONLY users
    ADD CONSTRAINT uk_email UNIQUE (email);

ALTER TABLE ONLY course
    ADD CONSTRAINT uk_code UNIQUE (code);

ALTER TABLE ONLY users
    ADD CONSTRAINT uk_username UNIQUE (username);

-- Foreign Keys
ALTER TABLE ONLY grades
    ADD CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES students(id);

ALTER TABLE ONLY grades
    ADD CONSTRAINT fk_grades_course FOREIGN KEY (course_id) REFERENCES course(id);
