-- V2: Add refresh tokens table for JWT authentication

CREATE TABLE refresh_tokens (
    id bigint NOT NULL,
    token character varying(500) NOT NULL,
    user_id bigint NOT NULL,
    expiry_date timestamp NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    revoked boolean DEFAULT FALSE
);

ALTER TABLE refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary Key
ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

-- Unique Constraint
ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT uk_refresh_token UNIQUE (token);

-- Foreign Key
ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- Index for performance
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
